# ============================================================================
#  dnsmasq.conf — Auto-generated by Terraform
#  Simulates multi-cloud DNS-based routing locally.
#  DO NOT edit manually — re-run `terraform apply` to regenerate.
# ============================================================================

# Listen on loopback only
listen-address=127.0.0.1
bind-interfaces
port=5353

# ── Primary Routing: AWS (default) ────────────────────
address=/${domain}/${aws_ip}
address=/www.${domain}/${aws_ip}
address=/aws.${domain}/${aws_ip}

# ── Secondary: Azure ──────────────────────────────────
address=/azure.${domain}/${azure_ip}

# ── Tertiary: GCP ─────────────────────────────────────
address=/gcp.${domain}/${gcp_ip}

# ── Health-check sub-domains ──────────────────────────
address=/health-aws.${domain}/${aws_ip}
address=/health-azure.${domain}/${azure_ip}
address=/health-gcp.${domain}/${gcp_ip}

# ── Logging ───────────────────────────────────────────
log-queries
log-facility=/var/log/dnsmasq.log

# ── Upstream DNS (fallback for real domains) ──────────
server=8.8.8.8
server=8.8.4.4
