#!/usr/bin/env bash
# ============================================================================
#  health_check.sh — Auto-generated by Terraform
#  Validates all three cloud endpoints + DNS resolution via DNSMasq
#  Usage: ./scripts/health_check.sh [--json] [--loop <interval_secs>]
# ============================================================================
set -euo pipefail

# ── Injected by Terraform ─────────────────────────────
AWS_IP="${aws_ip}"
AZURE_IP="${azure_ip}"
GCP_IP="${gcp_ip}"
DOMAIN="${domain}"

# ── Config ────────────────────────────────────────────
TIMEOUT=8
RETRIES=2
OUTPUT_JSON=false
LOOP_INTERVAL=0

# ── Colour codes ──────────────────────────────────────
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m';  BOLD='\033[1m';   NC='\033[0m'

# ── Parse args ────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --json)   OUTPUT_JSON=true; shift ;;
    --loop)   LOOP_INTERVAL="$2"; shift 2 ;;
    *)        echo "Unknown option: $1"; exit 1 ;;
  esac
done

PASS=0; FAIL=0; RESULTS=()

# ── Functions ─────────────────────────────────────────
banner() {
  echo -e "$${CYAN}$${BOLD}"
  echo "  ╔════════════════════════════════════════════════════════════╗"
  echo "  ║       TRI-CLOUD HEALTH CHECK — AWS + Azure + GCP          ║"
  echo "  ║       $(date -u '+%Y-%m-%d %H:%M:%S UTC')                         ║"
  echo "  ╚════════════════════════════════════════════════════════════╝"
  echo -e "$${NC}"
}

check_http() {
  local label="$1" url="$2" cloud="$3"
  local attempt=0 http_code="000"

  while [[ $attempt -lt $RETRIES ]]; do
    http_code=$(curl -s -o /tmp/hc_body_$$.txt -w "%{http_code}" \
      --max-time "$TIMEOUT" --connect-timeout 5 "$url" 2>/dev/null || echo "000")
    [[ "$http_code" == "200" ]] && break
    ((attempt++))
    sleep 1
  done

  if [[ "$http_code" == "200" ]]; then
    echo -e "  [$${GREEN}PASS$${NC}] $${BOLD}$label$${NC} ($url) → HTTP $http_code"
    RESULTS+=("{\"cloud\":\"$cloud\",\"check\":\"$label\",\"url\":\"$url\",\"status\":\"pass\",\"http\":$http_code}")
    ((PASS++))
  else
    echo -e "  [$${RED}FAIL$${NC}] $${BOLD}$label$${NC} ($url) → HTTP $http_code"
    RESULTS+=("{\"cloud\":\"$cloud\",\"check\":\"$label\",\"url\":\"$url\",\"status\":\"fail\",\"http\":$http_code}")
    ((FAIL++))
  fi
  rm -f /tmp/hc_body_$$.txt
}

check_health_json() {
  local label="$1" url="$2" cloud="$3"
  local body status

  body=$(curl -sf --max-time "$TIMEOUT" "$url" 2>/dev/null || echo "{}")
  status=$(echo "$body" | grep -o '"status":"[^"]*"' | cut -d'"' -f4 || echo "unknown")

  if [[ "$status" == "healthy" ]]; then
    echo -e "  [$${GREEN}PASS$${NC}] $label → status=$${GREEN}$status$${NC}"
    ((PASS++))
  else
    echo -e "  [$${RED}FAIL$${NC}] $label → status=$${RED}$status$${NC}"
    ((FAIL++))
  fi
}

check_dns() {
  local hostname="$1" expected_ip="$2"

  if command -v dig &>/dev/null; then
    resolved=$(dig +short @127.0.0.1 -p 5353 "$hostname" 2>/dev/null | head -1 || echo "unresolved")
  elif command -v nslookup &>/dev/null; then
    resolved=$(nslookup -port=5353 "$hostname" 127.0.0.1 2>/dev/null \
      | grep "Address:" | tail -1 | awk '{print $2}' || echo "unresolved")
  else
    resolved="dig/nslookup not installed"
  fi

  if [[ "$resolved" == "$expected_ip" ]]; then
    echo -e "  [$${GREEN}PASS$${NC}] DNS $hostname → $${GREEN}$resolved$${NC}"
    ((PASS++))
  else
    echo -e "  [$${YELLOW}WARN$${NC}] DNS $hostname → $resolved (expected $expected_ip)"
    ((FAIL++))
  fi
}

run_checks() {
  PASS=0; FAIL=0; RESULTS=()

  banner

  echo -e "$${YELLOW}$${BOLD}▶ AWS (us-east-1) — $AWS_IP$${NC}"
  check_http        "Landing Page"   "http://$${AWS_IP}/"       "AWS"
  check_http        "Health Route"   "http://$${AWS_IP}/health" "AWS"
  check_health_json "Health JSON"    "http://$${AWS_IP}/health/index.json" "AWS"
  echo ""

  echo -e "$${YELLOW}$${BOLD}▶ Azure (East US) — $AZURE_IP$${NC}"
  check_http        "Landing Page"   "http://$${AZURE_IP}/"       "Azure"
  check_http        "Health Route"   "http://$${AZURE_IP}/health" "Azure"
  check_health_json "Health JSON"    "http://$${AZURE_IP}/health/index.json" "Azure"
  echo ""

  echo -e "$${YELLOW}$${BOLD}▶ GCP (us-central1) — $GCP_IP$${NC}"
  check_http        "Landing Page"   "http://$${GCP_IP}/"       "GCP"
  check_http        "Health Route"   "http://$${GCP_IP}/health" "GCP"
  check_health_json "Health JSON"    "http://$${GCP_IP}/health/index.json" "GCP"
  echo ""

  echo -e "$${YELLOW}$${BOLD}▶ DNS Resolution (DNSMasq @127.0.0.1:5353)$${NC}"
  check_dns "$${DOMAIN}"             "$AWS_IP"
  check_dns "aws.$${DOMAIN}"         "$AWS_IP"
  check_dns "azure.$${DOMAIN}"       "$AZURE_IP"
  check_dns "gcp.$${DOMAIN}"         "$GCP_IP"
  echo ""

  # Summary
  TOTAL=$((PASS + FAIL))
  echo -e "  $${BOLD}══════════════════════════════════════════════════════════════$${NC}"
  echo -e "  $${BOLD}RESULTS:  $${GREEN}$${PASS} passed$${NC}  |  $${RED}$${FAIL} failed$${NC}  |  $TOTAL total checks$${NC}"
  echo -e "  $${BOLD}══════════════════════════════════════════════════════════════$${NC}"

  if $OUTPUT_JSON; then
    echo ""
    echo "JSON Output:"
    printf '[\n  %s\n]\n' "$(IFS=$',\n  '; echo "$${RESULTS[*]}")"
  fi

  [[ "$FAIL" -eq 0 ]] && return 0 || return 1
}

# ── Main ──────────────────────────────────────────────
if [[ "$LOOP_INTERVAL" -gt 0 ]]; then
  echo "Running health checks every $${LOOP_INTERVAL}s (Ctrl+C to stop)"
  while true; do
    run_checks || true
    echo "Sleeping $${LOOP_INTERVAL}s..."
    sleep "$LOOP_INTERVAL"
    clear
  done
else
  run_checks
fi
